[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['cd backend && npm run build || echo "No build script found"']

[start]
cmd = 'cd backend && npm start'