[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd backend && npm ci']

[phases.build]
cmds = ['cd backend && npm run build 2>/dev/null || echo "No build script, skipping"']

[start]
cmd = 'cd backend && npm start'